image: node:10.15.0

pipelines:
  branches:
    development:
    - step:
        name: deploy-to-s3
        deployment: test
        script: # Modify the commands below to build your repository.
        - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
        - apt-get update
        - apt-get install -y jq
        - apt-get install -y python-dev
        - apt-get install unzip
        - unzip awscli-bundle.zip
        - ./awscli-bundle/install -b ~/bin/aws
        - export PATH=~/bin:$PATH
        - cd client
        - npm install
        - REACT_APP_ALGOLIA_API_KEY=${REACT_APP_ALGOLIA_API_KEY} REACT_APP_ALGOLIA_APP_ID=${REACT_APP_ALGOLIA_APP_ID} REACT_APP_ALGOLIA_INDEX_NAME=${REACT_APP_ALGOLIA_INDEX_NAME} REACT_APP_ALGOLIA_AUTO_TAGS_INDEX_NAME=${REACT_APP_ALGOLIA_AUTO_TAGS_INDEX_NAME} REACT_APP_API_GATEWAY_REGION=${REACT_APP_API_GATEWAY_REGION} REACT_APP_API_GATEWAY_URL=${REACT_APP_API_GATEWAY_URL} REACT_APP_COGNITO_REGION=${REACT_APP_COGNITO_REGION} REACT_APP_USER_POOL_ID=${REACT_APP_USER_POOL_ID} REACT_APP_COGNITO_CLIENT_ID=${REACT_APP_COGNITO_CLIENT_ID} REACT_APP_ELB=${REACT_APP_ELB} npm run build && aws s3 cp ./build s3://${S3_BUCKET_NAME} --recursive
  