export const ERROR_MESSAGE_ADDED = 'ERROR_MESSAGE_ADDED';
export const ERROR_MESSAGE_DISMISSED = 'ERROR_MESSAGE_DISMISSED';
export const GENERATE_TERMS_SUCCESS = 'GENERATE_TERMS_SUCCESS';
export const CONSUME_TERMS_SUCCESS = 'CONSUME_TERMS_SUCCESS';
