export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const CREDENTIALS_UPDATED = 'CREDENTIALS_UPDATED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
